version: '3.8'


services:
  frontend:
    build: ./frontend

    image: hoquocnam92/frontend:latest
    
    ports:
      - "5173:80"
    depends_on:
      - backend
    networks:
      - app-net
  backend:
    build: ./backend

    image: hoquocnam92/backend:latest

    ports:
      - "8080:8080"
    depends_on:
      - db
    networks:
      - app-net
  db:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD : 123456
      MYSQL_DATABASE : bai3
    ports:
      - "3307:3306"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - app-net


networks:
  app-net: